lang:

warning_message:
    header: "&7■■■■■■■■■■ &2&lCONTACTEZ UN GARDIEN &7■■■■■■■■■■"
    message: "Nous vous invitons à &6cliquer ici pour venir sur le forum&r afin de vous expliquer dans le sujet approprié et, ainsi, retrouver un accès normal à Zcraft."
    link: "https://t.co"
    footer: "&7■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■"

warning_interval: 10  # Minutes

# If true, players in read-only mode cannot chat.
# Their blocked messages are still logged into the console, so you know
# what they tried to say.
block_chat: false

# These commands are executed when a player is put into, or removed from, read-only
# mode. You can use the following special tokens in the commands:
# - {player} replaced by the player name
# - {playerID} replaced by the player UUID
# - {moderator} replaced by the moderator name (or "<console>")
# - {moderatorID} replaced by the moderator UUID (or "<console>")
# - {reason} replaced by the read-only reason (just set or to be removed)
commands:
    readonly_enabled:
      -

    readonly_disabled:
      -
