lang:

warning_message:
    header: "&7■■■■■■■■■■ &c&lCONTACTEZ UN GARDIEN &7■■■■■■■■■■"
    message: "Nous vous invitons à &6venir sur le forum&r afin de vous expliquer dans le sujet approprié et, ainsi, retrouver un accès normal à Zcraft."
    link: "https://t.co"
    footer: "&7■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■"

warning_interval: 10  # Minutes

block_chat: false
