name: ReadOnlyWarning
description: Warns a player with a read-only word
main: fr.prokopowicz.alex.ReadOnlyWarning
version: 1.0
author: "Jenjeur"
authors:
  - "Amaury Carrade"

commands:
    ro:
        description: Places a player on the read only list
    unro:
        description: Removes a player from the read only list
    roinfos:
        description: Gives infos
